-- CARS
CREATE TABLE IF NOT EXISTS cars (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INT NOT NULL,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  color TEXT NOT NULL,
  vin TEXT,
  mileage TEXT,
  trim TEXT,
  notes TEXT,
  spec_id INT REFERENCES car_specs(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- indexes
CREATE INDEX IF NOT EXISTS idx_cars_vin ON cars(vin);
CREATE INDEX IF NOT EXISTS idx_cars_year ON cars(year);
CREATE INDEX IF NOT EXISTS idx_cars_make ON cars(make);
CREATE INDEX IF NOT EXISTS idx_cars_model ON cars(model);
CREATE INDEX IF NOT EXISTS idx_specs_plate ON car_specs(license_plate_number);